### PR TITLE
Fixing typo: onxy -> onyx

### PR DESCRIPTION
**Pull request by BlueRyth**
It was driving me nuts D:

### CODE REVIEW

**Comment by zachwlewis** [comment]
Why did you close the pull request, dorklord? :shipit:

**Comment by BlueRyth** [comment]
Uh, github freaked out. Like, I couldn't view pages and I got a bunch of
automated emails.

**Comment by zachwlewis** [comment]
Did canceling the request fix it?

**Comment by BlueRyth** [comment]
Nope, but I was just clicking buttons at that point

**Pull request merged**
